### ISSUE TITLE
Is engines entry in package.json working?

### ISSUE THREAD

**Issue by samli0413** [yargs/y18n#113]
Hi,
I am new to dev.  This is just a question rather an issue.  I noticed that in this commit https://github.com/yargs/y18n/commit/3cc0c287240727b84eaf1927f903612ec80f5e43, there is engines entry added in package.json file.  It indicates that the node version needs to be >=10.0.0.  However the command 'npm install y18n' happily installed 5.0.5 with no error or warning on node 8.0.0.  Am I missing something obviously?  Would you shed me some light on this please.

MacOS: Sierra
Version: 10.12.1
npm version: 6.13.0

Cheers
Sam

**Comment by bcoe** [comment]
Hey @samli0413 👋 

By default `npm` doesn't enforce the `engines` field, to enforce it you need to set `--engine-strict`:

https://docs.npmjs.com/cli/v6/using-npm/config#engine-strict

I've been doing this in CI/CD, so that I catch dependencies that are not guaranteed to work on my platform.

**Comment by samli0413** [comment]
Thanks mate for clarification.

Sam
