### ISSUE TITLE
v4.0.1?

### ISSUE THREAD

**Issue by abrown** [yargs/y18n#115]
Was [v4.0.1](https://www.npmjs.com/package/y18n/v/4.0.1) an official release? I was looking for it in the changelog and in the tags but do not see it.

**Comment by robertknight** [comment]
The change in this version is indeed a backport. It would help reviewers if the change was pushed to GitHub. The diff of the 4.0.0..4.0.1 npm package contents is available here: https://diff.intrinsic.com/y18n/4.0.0/4.0.1

**Comment by bcoe** [comment]
https://github.com/yargs/y18n/releases/tag/y18n-v4.0.2
