### ISSUE TITLE
Where is the v4.0.1 tag and code changes?

### ISSUE THREAD

**Issue by cristobal** [yargs/y18n#119]
I can't seem to find the `4.0.1` ([Prototype Pollution](https://npmjs.com/advisories/1654) fix), tag anywhere in the repo or in the [releases](https://github.com/yargs/y18n/releases?after=v5.0.2-deno) page.

![Screenshot 2021-04-06 at 10 25 20](https://user-images.githubusercontent.com/155505/113681574-6529eb80-96c2-11eb-886b-49aff92a594d.png)

I can see the that there are changes done in the generated output code for the v4.0.1 vs. v4.0.0 and it seems all good :) 👍🏽 

![Screenshot 2021-04-06 at 10 41 33](https://user-images.githubusercontent.com/155505/113683582-a91df000-96c4-11eb-8919-96c7344ff193.png)

I guess somebody perhaps forgot to push the local changes done and the tag for the v4.x.x branch to the Github Repo here. 

I think from a security perspective and keep the history it would be nice to have the changes pushed to the repo here. Otherwise like now some people may wonder if there are actual changes done, or if there is an malicious third party involved (which it's currently not).

**Comment by mikenicklas** [comment]
Running into this also. It would be great to have something to point at for context on what was changed and how it fixes the vulnerability.

**Comment by bcoe** [comment]
https://github.com/yargs/y18n/releases/tag/y18n-v4.0.2
