### ISSUE TITLE
{"correlation_id":"124.6195372936469","transaction_status":"approved","validation_status":"success","transaction_type":"purchase","transaction_id":"ET182228","transaction_tag":"4629487231","method":"credit_card","amount":"11","currency":"USD","cvv2":"P","token":{"token_type":"FDToken","token_data":{"value":"1814884572053939"}},"card":{"type":"visa","cardholder_name":"000200614860495","card_number":"3939","exp_date":"1224"},"bank_resp_code":"100","bank_message":"Approved","gateway_resp_code":"00","gateway_message":"Transaction Normal","retrieval_ref_no":"210427"}

### ISSUE THREAD

**Issue by kariukiandy** [yargs/y18n#135]
{"correlation_id":"124.6195372936469","transaction_status":"approved","validation_status":"success","transaction_type":"purchase","transaction_id":"ET182228","transaction_tag":"4629487231","method":"credit_card","amount":"11","currency":"USD","cvv2":"P","token":{"token_type":"FDToken","token_data":{"value":"1814884572053939"}},"card":{"type":"visa","cardholder_name":"000200614860495","card_number":"3939","exp_date":"1224"},"bank_resp_code":"100","bank_message":"Approved","gateway_resp_code":"00","gateway_message":"Transaction Normal","retrieval_ref_no":"210427"}

**Comment by firecoder1** [comment]
what
