### ISSUE TITLE
Published package should not include tests

### ISSUE THREAD

**Issue by mcalthrop** [yargs/y18n#20]
The npm package that is published should not include tests.

Background: running into problems in a project I'm working on that uses [flow](http://flowtype.org), which fails (understandably) when trying to process invalid JSON files that are in the `test` directory of this package.

Simple solution is to add a `.npmignore` file containing `test` (per [npm docs: keeping files out of your package](https://docs.npmjs.com/misc/developers#keeping-files-out-of-your-package)).

**Comment by mcalthrop** [comment]
I took the liberty of raising a PR (#21) – that should fix the issue! :-)

**Comment by Nitive** [comment]
I have the same problem.
Fast solution:
Add this in .flowconfig
```
[ignore]
.*/node_modules/y18n/test/locales/bad-locale.json
```

**Comment by balupton** [comment]
Just ran into this with flow.

Also, publishing the tests with the published package just pollutes the registry with unnecessary files slowing down mirrors and download times for everyone.

Solution is to use a `.npmignore` file. Here is ours: https://github.com/bevry/base/blob/master/.npmignore

**Comment by mcalthrop** [comment]
@balupton: yep. That's what I did in the PR.
