### ISSUE TITLE
args order in translations

### ISSUE THREAD

**Issue by jrappen** [yargs/y18n#42]
Assume a translation:

```json
//  locales/xx.json


{
    "one %s two %s three": ".... %s ... %s ..."
}
```

where the order of the args is reversed in the translated string. How do I handle this?

**Comment by bcoe** [comment]
@jrappen great question. How have you seen this approach in other `i18n` libraries? feels like we might need to extend on our functionality.

**Comment by jrappen** [comment]
@bcoe I've seen something along the lines of `... {0} ... {1} ... {2} ... {3} ...` where the numbers were the index of the args. Any translation could then simply rearrange like `... {2} ... {0} ... {3} ... {1} ...`.

**Comment by bcoe** [comment]
@jrappen what if we still supported `%s` for legacy translation files, but added support for this logic into the parser for folks who want to use it; then we'd simply detect the format (just grep for {0})

**Comment by jrappen** [comment]
@bcoe Either that or use named args like `.... {name} .... {project} ..... {user} ..... {whatever} ....`.

**Comment by jrappen** [comment]
closing as stale
