### ISSUE TITLE
Could we please publish a new version to npm?

### ISSUE THREAD

**Issue by JamesKyburz** [yargs/y18n#50]

**Comment by nexdrew** [comment]
@bcoe @maxrimue Any particular reason (other than the usual resource constraints 😉) we're sitting on the changes in master? [Looks like](https://github.com/yargs/y18n/compare/v3.2.1...master) the support for tagged template literals is the main difference.

I can confirm that running `standard-version` bumps y18n to 4.0.0. If we want, I can go ahead and tag/publish that as `next` in npm.

**Comment by nexdrew** [comment]
@JamesKyburz Just published version 4.0.0 with your changes, currently as a `next` dist-tag in npm. Would you mind testing against this and letting us know before we promote to latest?

**Comment by JamesKyburz** [comment]
@nexdrew Thanks `y18n@next` worked for me.

**Comment by nexdrew** [comment]
@JamesKyburz Awesome, thanks for testing and reporting back! I just promoted 4.0.0 to latest.

Thanks for opening this issue and for your patience! Sorry we let this slide for so long. Please let us know if you run into any other issues. Thanks!

**Comment by bcoe** [comment]
@nexdrew thanks \o/
