### ISSUE TITLE
SyntaxError: syntax error in /home/travis/build/jedmao/eclint/locales/zh_CN.json

### ISSUE THREAD

**Issue by gucong3000** [yargs/y18n#55]
I'm not modifying any [code](https://github.com/jedmao/eclint/blob/e2d3ef94a810ab15ba435e28115ff2d08cfc100b/lib/i18n.ts),  just to keep trying to build on Travis-ci.
About every 10 builds, [this error](https://travis-ci.org/jedmao/eclint/jobs/298892171#L1753) occurs one time.

I have no idea to solve this issue.

**Comment by QmarkC** [comment]
I was unable to duplicate a SyntaxError with the same `zh_CN.json` file. Looks like the `__` method call was missing on your proxy call.

`i18n('zh_CN')('CommandError: Missing required sub-command.')` output `TypeError: i18n(...) is not a function` for me.
`i18n('zh_CN').__('CommandError: Missing required sub-command.')` output `命令错误: 缺少必须的子命令。` for me.
